### ISSUE TITLE
Dice rolls no longer reading actor stats

### ISSUE THREAD

**Issue by BrucenGoose** [DerDiemen/eclipsephase#30] opened 2022-09-22 13:03 UTC
Heya! Thank you so much for putting this together, especially since Eclipse Phase is fairly niche.

A couple of issues have cropped up in a recent update. Went to see if it was other modules having issues but the problems persisted even in a fresh world.

The first one is that the energy armour value in any armour items appears to always return to null, regardless of what value is put into it. 

The second one is that actor stats don't appear to be detected when rolling skill checks, meaning the system always assumes they have a score of less than 0. Interestingly 
enough this only applies to newly created actor sheets, not previously existing ones.
I'll note that the chat dialogue also doesn't recognize their name, as if it isn't communicating with the actor sheet at all.

![image](https://user-images.githubusercontent.com/114160368/191754073-5b7fea7e-a341-4185-814e-3dd2d5fd7ae3.png)

**Comment by DerDiemen** [comment] 2022-09-23 05:28
Hey BrucenGoose,

Great catch! I found the roll-bug and will publish it today during the day.

As for armor: I was not able to reproduce this one. Can you tell me what exactly you're trying to do?

(I will be off this whole weekend, so armor will only be updated afterwards)

**Comment by DerDiemen** [comment] 2022-09-27 08:43
Hey @BrucenGoose ,

I have found the armor issue during another playtest myself. Thank you for raising it anyway! This bug will now be fixed in the new version 0.6.6.7

I hope it's not too late for your campaign :) 

All the best

**Closed by DerDiemen** 2022-09-27 08:43 UTC

**Comment by BrucenGoose** [comment] 2022-09-27 10:59
Oh! Sorry I didn't respond, no it went well! 

It's my friends first time playing, so we're starting it out with a lightly altered Xenovore game - they've been loving it so far!
Thanks, I appreciate it a lot.
