### ISSUE TITLE
Players are not able to manually edit the ammo amount of their weapons

### ISSUE THREAD

**Issue by ava5627** [DerDiemen/eclipsephase#54] opened 2023-09-08 22:25 UTC
Players are not able to edit the current ammo in their weapons. Neither the sidecar nor in the inventory works. The GM is able to edit in both places.

**Comment by DerDiemen** [comment] 2023-09-09 08:31
This is actually by design to prevent players from changing their ammo. If they need to reload they can use the reload button. 

For edge cases like „I‘ll take a bullet out of my magazine to do this McGyver thing“ this is something the GM has to allow anyway so they can then change the ammo manually. 

Thank you for reporting! Happy to discuss.

**Comment by DerDiemen** [comment] 2023-12-17 15:27
This has been implemented and will be part of the next release!

**Closed by DerDiemen** 2023-12-17 15:27 UTC
Labels: enhancement, planned for next release
